#!/bin/sh
# shellcheck disable=SC3043 disable=SC2016

# vidf - Version Manager for ESP-IDF.
#
# Copyright (C) 2026 Oscar Pernia
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Implemented as a POSIX-compliant shell function. To initialize the tool,
# this script must be executed directly at least once to trigger the installation.
# Subsequent executions and daily usage require sourcing the script to manage
# ESP-IDF environments correctly.
#
# This tool is inspired by NVM (Node Version Manager) project,
# but for managing ESP-IDF (Espressif IoT Development Framework) installations
# and environments.

# @formatter:off
{ # Ensures the entire script is downloaded
# @formatter:on

_VIDF_VERSION="0.1.0-devel"

_vidf_is_sourced ()
{
  if [ -n "$ZSH_VERSION" ]
  then
    case "$ZSH_EVAL_CONTEXT" in
      *:file:*|*:file|file:*|file)
        return 0
        ;;
    esac
  else  # Add additional POSIX-compatible shell names here, if needed.
    case "${0##*/}" in
      dash|-dash|bash|-bash|ksh|-ksh|sh|-sh)
        return 0
        ;;
    esac
  fi
  return 1
}

_vidf_echo()
{
  while [ "$#" -gt 1 ]
  do
    printf "%s " "$1"
    shift
  done
  printf "%s\n" "${1:-}"
}

_vidf_err()
{
  _vidf_echo "$@" >&2
}

_vidf_error()
{
  _vidf_err "$(_vidf_style_red)$*$(_vidf_style_reset)"
}

_vidf_warn()
{
  _vidf_err "$(_vidf_style_yellow)$*$(_vidf_style_reset)"
}

_vidf_info()
{
  _vidf_err "$(_vidf_style_cyan)$*$(_vidf_style_reset)"
}

_vidf_success()
{
  _vidf_err "$(_vidf_style_green)$*$(_vidf_style_reset)"
}

_vidf_has()
{
  type "${1-}" >/dev/null 2>&1
  return "$?"
}

_vidf_read_hex_bytes()
{
  dd bs="$1" count=1 2>/dev/null | od -An -t x1 | xargs
}

# {{{ Interactive function helpers
# These functions require user interaction

# You must pass to it at least 2 arguments, the predicate and the cancelled message.
# A default value is provided for this two, so you can pass empty strings.
_vidf_user_confirms()
{
  local predicate
  predicate="${1:-"Is this ok?"} [y/N]: "

  local cancelled
  cancelled="${2:-"Operation cancelled."}"

  printf "%s" "$predicate" >&2

  local opt
  local read_exit_code
  while true
  do
    read -r opt
    read_exit_code="$?"
    # Fixes visual bug where if you pipe `yes | vidf ...` you are going to
    # have the lines squished up on the same line.
    if ! [ -t 0 ] || [ "$read_exit_code" -ne 0 ]
    then
      _vidf_err ""
      [ "$read_exit_code" -ne 0 ] && break
    fi
    case "$opt" in
      [yY][eE][sS]|[yY])
        return 0
        ;;
      [nN][oO]|[nN]|"")
        break
        ;;
      *)
        printf "Please enter (y)es or (n)o: " >&2
        ;;
    esac
  done

  _vidf_error "$cancelled"
  return 1
}

# Must be run from subshell due to registering global traps
_vidf_menu_setup()
{
  if ! [ -t 2 ]
  then
    return 2
  fi

  local old_stty_var
  old_stty_var="$1"

  eval "$old_stty_var=\"\$(stty -g)\""

  # Recovery traps
  # shellcheck disable=2064
  trap "_vidf_menu_unsetup \"\$$old_stty_var\"; exit 1" INT TERM

  # These are permanent settings, must go after adding the recovery traps
  stty -icanon -echo min 1 time 0
  printf "\033[?25l" >&2
}

_vidf_menu_unsetup()
{
  local old_stty
  old_stty="$1"

  stty "$old_stty"
  printf '\033[?25h' >&2
}

_vidf_menu_down()
{
  printf "\033[%dE" "$1" >&2
}

_vidf_menu_up()
{
  printf "\033[%dF" "$1" >&2
}

_vidf_menu_right()
{
  printf "\033[%dC" "$1" >&2
}

_vidf_menu_left()
{
  printf "\033[%dD" "$1" >&2
}

_vidf_menu_first_render()
{
  # If you wish to render single selection menus, then pass empty prefix
  local prefix_unselected
  prefix_unselected="$1"
  shift

  local n_rows
  n_rows="$#"

  # Render first row as pointed
  _vidf_err " $(_vidf_style_green; _vidf_style_bold)>$(_vidf_style_reset)" \
    "${prefix_unselected:+"$prefix_unselected "}$1"
  shift

  local i
  for i in "$@"
  do
    _vidf_err "   ${prefix_unselected:+"$prefix_unselected "}$i"
  done

  # Leave cursor on row 0, which is the current row
  _vidf_menu_up "$n_rows"
}

_vidf_menu_render_single_selected()
{
  # Assume cursor is in column 1 of currently pointed row

  # shellcheck disable=2059
  printf " $(_vidf_style_bold; _vidf_style_green)\u2714$(_vidf_style_reset)\r" >&2
}

_vidf_menu_render_selected()
{
  # Assume cursor is in column 1 of currently pointed row

  # Move to the right 3 positions (possible " > " padding)
  _vidf_menu_right 3

  # shellcheck disable=2059
  printf "$(_vidf_style_bold)\uff3b$(_vidf_style_green)\u2714$(_vidf_style_uncolor)\uff3d$(_vidf_style_unbold)\r" >&2
}

_vidf_menu_render_unselected()
{
  # Assume cursor is in column 1 of currently pointed row

  # Move cursor to the right 3 positions (possible " > " padding)
  _vidf_menu_right 3

  # shellcheck disable=2059
  printf "$(_vidf_style_bold)\uff3b \uff3d$(_vidf_style_unbold)\r" >&2
}

_vidf_menu_unrender_pointer()
{
  # Assume cursor is in column 1 of currently pointed row

  printf "  \r" >&2
}

# Consumes bytes from stdin, and handles up/down arrow keystrokes, anything else is
# output to stdout.
#
# When it reaches EOF, it returns code 1
_vidf_menu_navigate()
{
  local cur_row_var
  cur_row_var="$1"

  local n_rows
  n_rows="$2"

  local byte_var
  byte_var="$3"

  eval "$byte_var=\"\$(_vidf_read_hex_bytes 1)\""
  case "$(eval "_vidf_echo \"\$$byte_var\"")" in
    "1b")
      ;;
    "")
      return 1
      ;;
    *)
      return 0
      ;;
  esac

  eval "$byte_var=\"\$(_vidf_read_hex_bytes 1)\""
  case "$(eval "_vidf_echo \"\$$byte_var\"")" in
    "5b")
      ;;
    "")
      return 1
      ;;
    *)
      eval "$byte_var=\"1b \$$byte_var\""
      return 0
      ;;
  esac

  eval "$byte_var=\"\$(_vidf_read_hex_bytes 1)\""
  case "$(eval "_vidf_echo \"\$$byte_var\"")" in
    "41" | "42")
      ;;
    "")
      return 1
      ;;
    *)
      eval "$byte_var=\"1b 5b \$$byte_var\""
      return 0
      ;;
  esac

  _vidf_menu_unrender_pointer

  case "$(eval "_vidf_echo \"\$$byte_var\"")" in
    "41")
      if [ "$(eval "_vidf_echo \"\$$cur_row_var\"")" -gt 0 ]
      then
        eval "$cur_row_var=\"\$(($cur_row_var - 1))\""

        _vidf_menu_up 1
      else
        # Wrap-around
        eval "$cur_row_var=\"\$((n_rows - 1))\""
        if [ "$n_rows" -gt 1 ]
        then
          _vidf_menu_down "$((n_rows - 1))"
        fi
      fi
      ;;
    "42")
      if [ "$(eval "_vidf_echo \"\$$cur_row_var\"")" -lt "$((n_rows - 1))" ]
      then
        eval "$cur_row_var=\"\$(($cur_row_var + 1))\""
        _vidf_menu_down 1
      else
        # Wrap-around
        eval "$cur_row_var=0"

        if [ "$n_rows" -gt 1 ]
        then
          _vidf_menu_up "$((n_rows - 1))"
        fi
      fi
      ;;
  esac

  # Write " > " indicator onto new position
  # shellcheck disable=2059
  printf " $(_vidf_style_bold; _vidf_style_green)>$(_vidf_style_reset)\r" >&2
  return 0
}

# Outputs to stdout the index of the argument that the user selected
_vidf_user_single_select()
(
  # Using a subshell so `exit` inside traps safely returns from the function without killing the parent shell.

  local old_stty
  _vidf_menu_setup old_stty || return

  local title
  title="$1"
  shift

  _vidf_err "$(_vidf_style_bold)--- $title ---$(_vidf_style_unbold)"
  _vidf_err "Use $(_vidf_style_bold)[Up/Down Arrows]$(_vidf_style_unbold) to navigate, and" \
    "$(_vidf_style_bold)[Enter]$(_vidf_style_unbold) to confirm."

  local cur_row
  cur_row=0

  local n_rows
  n_rows="$#"

  local byte

  _vidf_menu_first_render "" "$@"

  while true
  do
    if ! _vidf_menu_navigate cur_row "$n_rows" byte
    then
      _vidf_error "Unexpected EOF, Ctrl+D was pressed"
      return 1
    fi
    case "$byte" in
      "0a")
        # Enter key pressed

        _vidf_menu_render_single_selected
        _vidf_menu_down "$((n_rows - cur_row))"
        break
        ;;
    esac
  done

  _vidf_menu_unsetup "$old_stty"

  _vidf_echo "$cur_row"

  return 0
)

# Outputs to stdout the selected options as an space-separated quoted list
_vidf_user_multi_select()
(
  # Using a subshell so `exit` inside traps safely returns from the function without killing the parent shell.

  local old_stty
  _vidf_menu_setup old_stty || return

  local title
  title="$1"
  shift

  local n_rows
  n_rows="$#"
  local cur_row
  cur_row=0

  local byte

  local menu_state
  # Array of objects, with keys "name" and "selected"
  menu_state="$(jq -nc '$ARGS.positional | map({"name": ., "selected": false})' --args -- "$@")"

  _vidf_err "$(_vidf_style_bold)--- $title ---$(_vidf_style_unbold)"
  _vidf_err "Use $(_vidf_style_bold)[Up/Down Arrows]$(_vidf_style_unbold) to navigate," \
    "$(_vidf_style_bold)[Space]$(_vidf_style_unbold) to toggle, and" \
    "$(_vidf_style_bold)[Enter]$(_vidf_style_unbold) to confirm."

  _vidf_menu_first_render "$(_vidf_style_bold)$(printf "\uff3b \uff3d")$(_vidf_style_unbold)" "$@"

  while true
  do
    if ! _vidf_menu_navigate cur_row "$n_rows" byte
    then
      _vidf_error "Unexpected EOF, Ctrl+D was pressed"
      return 1
    fi
    case "$byte" in
      "20")
        # Space key pressed

        menu_state="$(_vidf_echo "$menu_state" | jq -c ".[$cur_row].selected |= not")"
        if [ "$(_vidf_echo "$menu_state" | jq -r ".[$cur_row].selected")" = true ]
        then
          _vidf_menu_render_selected
        else
          _vidf_menu_render_unselected
        fi
        ;;
      "0a")
        # Enter key pressed

        _vidf_menu_unrender_pointer
        _vidf_menu_down "$((n_rows - cur_row))"
        break
        ;;
    esac
  done

  _vidf_menu_unsetup "$old_stty"

  local line
  _vidf_echo "$menu_state" | jq -r '.[] | select(.selected) | .name' |
  while IFS="" read -r line
  do
    printf " %s" "$(_vidf_sanitize_arg "$line")"
  done

  _vidf_echo ""

  return 0
)

# }}}

_vidf_app_dir()
{
  local app_dir
  app_dir="${VIDF_DIR:-"$HOME/.vidf"}"

  if [ "$app_dir" = "${app_dir#/}" ]
  then
    if [ -n "${VIDF_DIR:-}" ]
    then
      _vidf_error "$(_vidf_style_underline)VIDF_DIR$(_vidf_style_ununderline)" \
        "variable must be an absolute path."
    else
      _vidf_error "$(_vidf_style_underline)HOME$(_vidf_style_ununderline)" \
        "variable must be an absolute path."
    fi
    return 1
  fi

  _vidf_echo "$app_dir"
  return 0
}

_vidf_cache_dir()
{
  local cache_dir
  cache_dir="$XDG_CACHE_HOME"
  if [ "$cache_dir" = "${cache_dir#/}" ]
  then
    cache_dir="$HOME/.cache"
  fi
  cache_dir="$cache_dir/vidf"
  _vidf_echo "$cache_dir"
  return 0
}

# Downloads a file using curl, and saves it into the app cache directory,
# it also saves a .etag file that stores the resource's ETag the server returned,
# to be send in future requests to help with server-side caching.
#
# It outputs to stdout the downloaded file path
_vidf_download_file()
{
  local url
  url="$1"

  local filepath
  filepath="$(_vidf_cache_dir)"
  if ! mkdir -p "$filepath"
  then
    _vidf_error "Couldn't create cache directory: $(_vidf_style_bold)$filepath$(_vidf_style_unbold)"
    return 2
  fi

  local filename
  filename="$(basename "$url")"

  filepath="$filepath/$filename"

  local etag_path
  etag_path="$filepath.etag"

  if ! curl -fSsLo "$filepath" --etag-save "$etag_path" --etag-compare "$etag_path" "$url"
  then
    _vidf_error "Failed to download $(_vidf_style_bold)$filename$(_vidf_style_unbold)." \
      "Try again later."
    return 2
  fi

  _vidf_echo "$filepath"
  return 0
}

# Argument-handling functions {{{

# Output is already quoted.
_vidf_sanitize_arg()
{
  local sanitized

  sanitized="$(printf "%s" "$1" | sed "s/'/'\\\\''/g")"

  printf "'%s'" "$sanitized"
}

# Canonizes flags, converts them from the form:
#
#   --foo=bar -abc
#
# To:
#
#   --foo 'bar' -a -b -c
#
# The $1 format is similar to the one on _vidf_check_args, except that you must
# trim the arguments range from the beginning, e.g:
#
# "-y,--prefix:,-h,--help"
_vidf_canonize_args()
{
  local flags
  # Normalize flags, separate in newlines, apply colons to all aliases that
  # end on colon (:), and finally one last separation with newlines of aliases.
  # We don't use the slashes because this command is indifferent regarding aliases,
  # aliases overwrite other aliases.
  flags="$(_vidf_echo "$1" | awk '
    BEGIN {
      FS = ","

      short_opts = ""
      long_opts = ""
    }
    {
      for (i = 1; i <= NF; i++)
        {
          alias_group = $i
          has_colon = sub(/:$/, "", alias_group) > 0
          n_aliases = split(alias_group, aliases, "/")
          for (j = 1; j <= n_aliases; j++)
            {
              alias = aliases[j] (has_colon ? ":" : "")

              if (sub(/^--/, "", alias))
                {
                  long_opts = (long_opts == "") ? alias : long_opts "," alias
                }
              else
                {
                  sub(/^-/, "", alias)
                  short_opts = short_opts alias
                }
            }
        }
    }
    END {
      print short_opts, long_opts
    }
  ')"
  shift

  local short_opts
  short_opts="${flags%" "*}"
  local long_opts
  long_opts="${flags#*" "}"

  local temp_err
  temp_err="$(mktemp)"

  local getopt_exit_code
  getopt_exit_code=0
  if ! LANGUAGE=C getopt -o "$short_opts" -l "$long_opts" -- "$@" 2>"$temp_err"
  then
    getopt_exit_code=1
    _vidf_error "$(sed -E 's/^getopt:\s*(.)/\u\1/' "$temp_err")"
  fi

  rm -rf "$temp_err"
  return "$getopt_exit_code"
}

# Same as _vidf_canonize_args, but the output of this function is safe to be
# passed to `eval` command in order to set the canonized arguments.
_vidf_canonize_args_eval()
{
  local flags
  flags="$1"
  shift

  local parsed_args

  if ! parsed_args="$(_vidf_canonize_args "$flags" "$@")"
  then
    _vidf_echo "false"
    return 0
  fi

  printf "set -- %s\n" "$parsed_args"

  return 0
}

# NOTE: We don't use getopts because it doesn't accept long options
#
# The $1 format parameter is similar to getopts format, except that
# it starts with the minimum and maximum number of required positional
# arguments, followed by a comma-separated list of valid short and long
# options. You can also pass a plus sign (+) after the minimum required
# positional arguments to indicate the user can pass infinite arguments.
# You can also pass aliased flags, you can have multiple aliased flags.
#
# User arguments must be canonized with _vidf_canonize_args_eval function.
#
# Basic format:
# "2,-y,--prefix:,--version"
#
# Format for variadic arguments, minimum 0 args and maximum 2 args:
# "0-2,-y,--prefix:,--version"
#
# Infinite arguments, minimum 1:
# "1+,-y,--prefix:,--version"
#
# Aliased flags:
# "2,-y/--yes,-p/--prefix:"
_vidf_check_args()
{
  local format
  format="$1"
  shift

  local expected_arg_range
  expected_arg_range="${format%%,*}"

  local flags
  flags="${format#*,}"

  # Separate in newlines for better handling.
  flags="$(_vidf_echo "$flags" | sed 's/,/\n/g')"

  local expected_min_args
  local expected_max_args
  case "$expected_arg_range" in
    *+)
      expected_min_args="${expected_arg_range%+}"
      expected_max_args=-1
      ;;
    *-*)
      expected_min_args="${expected_arg_range%%-*}"
      expected_max_args="${expected_arg_range#*-}"
      ;;
    *)
      expected_min_args="$expected_arg_range"
      expected_max_args="$expected_arg_range"
      ;;
  esac

  local arg_count
  arg_count=0

  local matched_flag

  while [ "$#" -gt 0 ]
  do
    case "$1" in
      --)
        shift
        arg_count="$((arg_count + $#))"
        break
        ;;
      -*[!-a-zA-Z0-9]*)
        # Contains invalid characters.
        _vidf_error "Unrecognized option '$1'"
        return 1
        ;;
      -*)
        if ! matched_flag="$(_vidf_echo "$flags" | grep -E "(^|/)$1(:|\$|/)")"
        then
          _vidf_error "Unrecognized option '$1'"
          return 1
        fi

        if [ "$matched_flag" != "${matched_flag%:}" ]
        then
          if [ "$#" -lt 2 ]
          then
            _vidf_error "Option '$1' requires an argument"
            return 1
          fi

          shift 2
          continue
        fi

        shift
        continue
        ;;
      *)
        arg_count=$((arg_count + 1))
        shift
        ;;
    esac
  done

  if [ "$arg_count" -lt "$expected_min_args" ]
  then
    _vidf_error "Too few arguments. Expected at least $expected_min_args, got $arg_count."
    return 1
  fi

  if [ "$expected_max_args" -ne -1 ] && [ "$arg_count" -gt "$expected_max_args" ]
  then
    _vidf_error "Too many arguments. Expected at most $expected_max_args, got $arg_count."
    return 1
  fi
}

# This function outputs to stdout a shell program to be eval'd by the caller,
# which is going to parse the arguments/flags of the user, and save it to
# flag variables specified on $2, and the parsed positional arguments are going
# to be saved on the caller's argument list, e.g. $1, $2, $3, ..., $N, etc.
#
# Function's parameters:
#
# - $1: Format specifier, see _vidf_check_args.
#
# - $2: Comma-separated flag shell variables list, their positions must correspond to
# the positions on the format specifier, if the format specifier doesn't list
# any flags, then you MUST NOT pass this argument, not even an empty string,
# you must directly pass the user's $@ list after $1.
#
# - $@: User's arguments, must be canonized.
_vidf_parse_args_eval()
{
  local format
  format="$1"
  shift

  local flag_vars
  [ -n "${format#*,}" ] && flag_vars="$1" && shift

  if ! _vidf_check_args "$format" "$@"
  then
    _vidf_echo "false"
    return 0
  fi

  local expected_flags
  expected_flags="${format#*,}"

  # Separate in newlines for better handling
  expected_flags="$(printf "%s" "$expected_flags" | sed 's/,/\n/g')"
  flag_vars="$(printf "%s" "$flag_vars" | sed 's/,/\n/g')"

  local matched_flag
  local target_var
  local flag_line_num

  local set_args_eval
  while [ "$#" -gt 0 ]
  do
    case "$1" in
      --)
        shift
        while [ "$#" -gt 0 ]
        do
          set_args_eval="$set_args_eval $(_vidf_sanitize_arg "$1")"
          shift
        done
        break
        ;;
      -*)
        matched_flag="$(_vidf_echo "$expected_flags" | awk '
          /(^|\/)'"$1"'(:|$|\/)/ {
            print NR, $0
            exit
          }
        ')"

        flag_line_num="${matched_flag%%" "*}"
        matched_flag="${matched_flag#*" "}"

        target_var="$(_vidf_echo "$flag_vars" | sed -n "${flag_line_num}p")"

        if [ "$matched_flag" != "${matched_flag#*:}" ]
        then
          shift
          _vidf_echo "$target_var=$(_vidf_sanitize_arg "$1")"
        else
          _vidf_echo "$target_var=1"
        fi
        ;;
      *)
        set_args_eval="$set_args_eval $(_vidf_sanitize_arg "$1")"
        ;;
    esac
    shift
  done

  printf "set --%s\n" " $set_args_eval"
}

# Returns the first argument that is not an option nor its value.
#
# $@ - User's arguments, this are required to be non-canonized due to the fact
#      that the subcommand is treated as a regular positional argument.
_vidf_find_subcommand()
{
  local skip_arg
  skip_arg=0
  local i

  for i in "$@"
  do
    if [ "$skip_arg" = 1 ]
    then
      skip_arg=0
      continue
    fi

    case "$i" in
      --color)
        # Add to pattern above known global options on canonical form that
        # contains a value.
        skip_arg=1
        ;;
      -*)
        ;;
      *)
        local subcommand
        subcommand="$i"
        [ -z "$subcommand" ] && return 1
        _vidf_echo "$subcommand"
        return 0
        ;;
    esac
  done

  return 1
}

# Removes the subcommand and return everything else as an space separated list.
#
# $@ - User's arguments, this are required to be non-canonized due to the fact
#      that the subcommand is treated as a regular positional argument.
_vidf_filter_subcommand()
{
  if [ "$#" -lt 1 ]
  then
    return 0
  fi

  local subcommand_found
  subcommand_found=0
  local skip_arg
  skip_arg=0
  local i
  for i in "$@"
  do
    if [ "$skip_arg" = 1 ] || [ "$subcommand_found" = 1 ]
    then
      skip_arg=0
      printf " %s" "$(_vidf_sanitize_arg "$i")"
      continue
    fi

    case "$i" in
      --color)
        skip_arg=1
        printf " %s" "$(_vidf_sanitize_arg "$i")"
        ;;
      -*)
        printf " %s" "$(_vidf_sanitize_arg "$i")"
        ;;
      *)
        subcommand_found=1
        ;;
    esac
  done

  _vidf_echo ""
}

# See _vidf_filter_subcommand, outputs a program to be eval'd by the caller,
# which is going to filter out the subcommand from user's arguments.
# You must have already called _vidf_find_subcommand in order to get the subcommand
# before eval'ing this function's output, and pass that as the first argument.
_vidf_filter_subcommand_eval()
{
  printf "set -- %s" "$(_vidf_filter_subcommand "$@")"
}

# }}}

# Git-related functions {{{

# Helper functions:

_vidf_git_base()
{
  local install_dir
  install_dir="$1"
  shift
  git --git-dir="$install_dir/.git" "$@"
}

_vidf_git_wt()
{
  local install_dir
  install_dir="$1"
  shift
  if [ "$1" = "submodule" ]
  then
    # Old bug with git submodule, it dates back to 2018. See:
    #
    # https://stackoverflow.com/questions/48767595/
    #
    # You have to cd into the working directory, since git submodule doesn't
    # respect --work-tree option
    _vidf_git_base "$install_dir" --work-tree="$install_dir" -C "$install_dir" "$@"
  else
    _vidf_git_base "$install_dir" --work-tree="$install_dir" "$@"
  fi
}

# Initializes a git repository.
_vidf_git_init()
{
  local install_dir
  install_dir="$1"

  if ! mkdir -p "$install_dir"
  then
    _vidf_error "Failed to create directory" \
      "$(_vidf_style_bold)$install_dir$(_vidf_style_unbold)"
    return 2
  fi

  if ! _vidf_git_base "$install_dir" init "$install_dir" -q
  then
    _vidf_error "Failed to initialize git repository on" \
      "$(_vidf_style_bold)$install_dir$(_vidf_style_unbold)"
    return 2
  fi

  return 0
}

# Fetches the version tag or branch, switches the repository to use that version,
# And updates any present submodules recursively. Additionally, it prunes the repository,
# which is very useful for long-living installations, such as ESP-IDF.
#
# This works for any repository, not only vidf's, e.g. ESP-IDF's.
_vidf_git_switch()
{
  local install_dir
  install_dir="$1"
  local repo_url
  repo_url="$2"
  local version_tag
  version_tag="$3"

  if ! _vidf_git_base "$install_dir" remote add origin "$repo_url" 2>/dev/null \
    && ! _vidf_git_base "$install_dir" remote set-url origin "$repo_url" 2>/dev/null
  then
    _vidf_error "Failed to add/set git remote origin" \
      "$(_vidf_style_bold)$repo_url$(_vidf_style_bold)"
    return 2
  fi

  # Fetch tag first
  local temp_err
  temp_err="$(mktemp)"

  local git_exit_code
  _vidf_git_wt "$install_dir" fetch origin tag "$version_tag" --depth=1 -j"$(nproc)" 2>"$temp_err"
  git_exit_code="$?"

  # Remove fatal lines from output, in order to not panic the user.
  sed -E '/^fatal:/d' "$temp_err" >&2
  rm -f "$temp_err"

  if [ "$git_exit_code" -ne 0 ] \
    && ! _vidf_git_wt "$install_dir" fetch origin "$version_tag" --depth=1 -j"$(nproc)"
  then
    _vidf_error "Failed to git fetch version" \
      "$(_vidf_style_bold)$version_tag$(_vidf_style_unbold)"
    return 2
  fi

  if ! _vidf_git_wt "$install_dir" switch -qdf FETCH_HEAD
  then
    _vidf_error "Failed to git switch to version" \
      "$(_vidf_style_bold)$version_tag$(_vidf_style_bold)"
    return 2
  fi

  if ! _vidf_git_wt "$install_dir" submodule update --init --recursive --depth=1 -j"$(nproc)"
  then
    _vidf_error "Failed to update the submodules"
    return 2
  fi

  # Don't use `git submodule update --force` above, it's very slow on ESP-IDF project
  # and big repos, use `git submodule foreach` optimization instead.
  if ! _vidf_git_wt "$install_dir" submodule foreach --recursive -q '
    desc="$(git describe --tags --dirty --always)" || exit 1
    if ! printf "%s" "$desc" | grep -qE -- "-dirty$"
    then
      # Continue foreach
      exit 0
    fi
    git switch -qdf "$sha1"
  ' >/dev/null 2>&1
  then
    _vidf_error "Failed to dirty-repair the submodules"
    return 2
  fi


  _vidf_info "Pruning git repository..."

  _vidf_git_base "$install_dir" -c gc.reflogExpire=now -c gc.reflogExpireUnreachable=now \
    gc --aggressive --prune=now >/dev/null 2>&1

  return 0
}

# Ensures git repository exists, fetches version tag or branch, and switches the repository
# to use that version.
#
# Is a combination of `git init`, `git fetch` and `git switch` all-in-one.
_vidf_git_ensure_switch()
{
  local install_dir
  install_dir="$1"
  local repo_url
  repo_url="$2"
  local version_tag
  version_tag="$3"

  _vidf_git_init "$install_dir"
  _vidf_git_switch "$install_dir" "$repo_url" "$version_tag"
}

_vidf_git_remote_tag_exists()
{
  local repo_url
  repo_url="$1"
  local remote_target
  remote_target="$2"

  if git ls-remote --exit-code --refs "$repo_url" \
    "refs/tags/$remote_target" "refs/heads/$remote_target" >/dev/null 2>&1
  then
    return 0
  fi

  return 1
}

_vidf_git_describe_dirty()
{
  local install_dir
  install_dir="$1"

  local cur_version

  _vidf_git_wt "$install_dir" describe --tags --exact-match --dirty 2>/dev/null ||
  _vidf_git_wt "$install_dir" describe --exact-match --dirty 2>/dev/null
}

# }}}

# ANSI color styles logic. {{{

_VIDF_COLOR=1

_vidf_style_setup()
{
  if [ "$#" -gt 0 ]
  then
    if [ "$1" = 1 ]
    then
      _VIDF_COLOR=1
    else
      _VIDF_COLOR=0
    fi
  elif [ -t 1 ]
  then
    _VIDF_COLOR=1
  else
    _VIDF_COLOR=0
  fi
}

_vidf_style_reset()
{
  [ "$_VIDF_COLOR" = "1" ] && printf "\033[0m"
}

_vidf_style_bold()
{
  [ "$_VIDF_COLOR" = "1" ] && printf "\033[1m"
}

_vidf_style_underline()
{
  [ "$_VIDF_COLOR" = "1" ] && printf "\033[4m"
}

_vidf_style_red()
{
  [ "$_VIDF_COLOR" = "1" ] && printf "\033[31m"
}

_vidf_style_green()
{
  [ "$_VIDF_COLOR" = "1" ] && printf "\033[32m"
}

_vidf_style_yellow()
{
  [ "$_VIDF_COLOR" = "1" ] && printf "\033[33m"
}

_vidf_style_cyan()
{
  [ "$_VIDF_COLOR" = "1" ] && printf "\033[36m"
}

_vidf_style_unbold()
{
  [ "$_VIDF_COLOR" = "1" ] && printf "\033[22m"
}

_vidf_style_ununderline()
{
  [ "$_VIDF_COLOR" = "1" ] && printf "\033[24m"
}

_vidf_style_uncolor()
{
  [ "$_VIDF_COLOR" = "1" ] && printf "\033[39m"
}

# }}}

# Rendering help message logic. {{{
# Simple manpage-like help message.

_vidf_help_render()
{
  local line
  while IFS="" read -r line
  do
    case "$line" in
      USAGE|COMMANDS|"GLOBAL OPTIONS")
        # Title sections styles
        printf "%s%s" "$(_vidf_style_bold)" "$line"
        ;;
      "$(printf "%*s" 4 "")"[a-zA-Z0-9]*)
        # Commands styles
        printf "%s%s" "$(_vidf_style_bold)" "$line"
        ;;
      "$(printf "%*s" 12 "")"-*)
        # Command option styles
        printf "%s%s" "$(_vidf_style_bold)" "$line"
        ;;
      *)
        # Bypass styles
        printf "%s" "$line"
        ;;
    esac
    printf "%s\n" "$(_vidf_style_reset)"

  done << EOF # You can add more styles to the here-doc below if the above ones doesn't fully style it.

vidf - Version Manager for ESP-IDF ($(vidf --version))

USAGE
    vidf <command> [options ...] [--] [arguments ...]

COMMANDS
    self-update [$(_vidf_style_underline)version$(_vidf_style_ununderline)]
        Updates $(_vidf_style_bold)vidf$(_vidf_style_unbold) to the latest release. $(:
        )If a specific $(_vidf_style_underline)version$(_vidf_style_ununderline) $(:
        )is provided, that version will be installed instead.

        Options:
            -y
                Automatic yes to all prompts.

    install [$(_vidf_style_underline)version$(_vidf_style_ununderline)]
        Installs $(_vidf_style_bold)ESP-IDF$(_vidf_style_unbold) latest release. If a specific $(:
        )$(_vidf_style_underline)version$(_vidf_style_ununderline) is provided, that version will $(:
        )be installed instead.

        Options:
            -y
                Automatic yes to all prompts.

            --repair
                Repairs the $(_vidf_style_bold)ESP-IDF$(_vidf_style_unbold) installation if $(:
                )it's $(_vidf_style_bold)dirty$(_vidf_style_unbold) (git detected modifications) $(:
                )or $(_vidf_style_bold)corrupted$(_vidf_style_unbold).

GLOBAL OPTIONS
    -h, --help
        Shows this message.

    --color <$(_vidf_style_underline)WHEN$(_vidf_style_ununderline)>
        Controls color output. Can be 'always', 'never', or 'auto' (default).

    -v, --version
        Prints currently installed vidf version and exits.

    --
        Delimits end of option processing. Any subsequent arguments
        are treated strictly as positional arguments.
EOF
}

# }}}

vidf()
{
  # Handle shell flags first, this is in order to avoid any unexpected
  # behaviours before executing any important commands that modifies the system.

  local default_ifs
  default_ifs=" $(_vidf_echo t | command tr t \\t)
"
  case "$-" in
    *e*)
      set +e
      local exit_code
      IFS="$default_ifs" vidf "$@"
      exit_code="$?"
      set -e
      return "$exit_code"
      ;;
    *a*)
      set +a
      local exit_code
      IFS="$default_ifs" vidf "$@"
      exit_code="$?"
      set -a
      return "$exit_code"
      ;;
    *E*)
      # Only if running on Bash
      if [ -n "${BASH-}" ]
      then
        # shellcheck disable=SC3041
        set +E
        local exit_code
        IFS="$default_ifs" vidf "$@"
        exit_code="$?"
        # shellcheck disable=SC3041
        set -E
        return "$exit_code"
      fi
      ;;
    *)
      if [ "$IFS" != "$default_ifs" ]
      then
        IFS="$default_ifs" vidf "$@"
        return "$?"
      fi
      ;;
  esac

  # First setup based on tty detection.
  _vidf_style_setup

  # {{{
  # Extract and filter out subcommand, canonize user's arguments, filter and
  # handle all global options from the canonized arguments.

  # Find subcommand
  local subcommand
  subcommand="$(_vidf_find_subcommand "$@")"

  # Filter out subcommand
  eval "$(_vidf_filter_subcommand_eval "$@")"

  local global_format
  global_format="--help,-h,--version,-v,--color:"

  # Add here additional options for each subcommand, they must not conflict
  # with the global options names.
  case "$subcommand" in
    self-update)
      global_format="$global_format,-y"
      ;;
    install)
      global_format="$global_format,-y,--repair"
      ;;
  esac

  # Canonize the arguments.
  if ! eval "$(_vidf_canonize_args_eval "$global_format" "$@")"
  then
    return 1
  fi

  local i
  local eoo # End Of Options, is -- present?
  eoo=0
  local flag_action

  local invalid_value
  invalid_value=0

  local skip_arg
  skip_arg=0

  local err_msg

  # Handle global options
  for i in "$@"
  do
    # Circular shift filter, in order to remove global options.
    shift

    if [ "$skip_arg" = 1 ]
    then
      skip_arg=0
      continue
    fi

    if [ "$eoo" = 1 ]
    then
      set -- "$@" "$i"
      continue
    fi

    case "$i" in
      --)
        eoo=1
        set -- "$@" "$i"
        ;;
      -h|--help)
        flag_action=help
        ;;
      --color)
        case "$1" in
          always)
            _vidf_style_setup 1
            ;;
          never)
            _vidf_style_setup 0
            ;;
          auto)
            _vidf_style_setup
            ;;
          *)
            err_msg="$(printf "%s${err_msg:+"\n"}Invalid value for --color: '%s'" "$err_msg" "$1")"
            invalid_value=1
            ;;
        esac

        skip_arg=1
        ;;
      -v|--version)
        # Add here the flag actions that may have higher priority
        case "$flag_action" in
          help)
            :
            ;;
          *)
            flag_action=version
            ;;
        esac
        ;;
      *)
        set -- "$@" "$i"
        ;;
    esac
  done

  # }}}
  # End of canonization, at this point the we've handled global options.

  if [ "$invalid_value" = 1 ]
  then
    _vidf_error "$err_msg"
    _vidf_help_render >&2
    return 1
  fi

  # Early return, before handling flag actions
  if [ "$_VIDF_STYLE_SETUP" = 1 ]
  then
    return 0
  fi

  case "$flag_action" in
    help)
      _vidf_help_render
      return 0
      ;;
    version)
      _vidf_echo "$_VIDF_VERSION"
      return 0
      ;;
  esac

  if [ -z "$subcommand" ]
  then
    _vidf_error "You must specify a subcommand."
    _vidf_help_render >&2
    return 1
  fi

  # Guard-clause for subcommands that require the app dir to be present.
  case "$subcommand" in
    self-update)
      # self-update doesn't require app dir to be present, since it creates it.
      ;;
    install)
      # Add to pattern above subcommands that require the app dir to be present
      if ! [ -d "$(_vidf_app_dir)" ]
      then
        _vidf_error "$(_vidf_style_bold)vidf$(_vidf_style_unbold) installation not found."
        _vidf_info "To install it, run: $(_vidf_style_bold)vidf self-update$(_vidf_style_unbold)"
        _vidf_info "Or execute the installer directly: $(_vidf_style_bold)./vidf$(_vidf_style_unbold)"
        return 1
      fi
      ;;
  esac

  case "$subcommand" in
    self-update)
      if ! _vidf_has git
      then
        _vidf_error "$(_vidf_style_bold)git$(_vidf_style_unbold) not found on" \
          "$(_vidf_style_underline)PATH$(_vidf_style_ununderline)," \
          "this is a required dependency for the" \
          "$(_vidf_style_bold)self-update$(_vidf_style_unbold) subcommand."
        return 1
      fi

      local yes_flag
      if ! eval "$(_vidf_parse_args_eval 0-1,-y yes_flag "$@")"
      then
        return 1
      fi

      local root_dir
      if ! root_dir="$(_vidf_app_dir)"
      then
        return 1
      fi

      # Where vidf is going to be cloned into.
      local install_dir
      install_dir="$root_dir/vidf"

      # Decentralizing and supporting forks, while I solve the problem
      # of distributing the tool through more secure package managers.
      local repo_url
      repo_url="${VIDF_SELF_UPDATE_GIT_URL:-"https://github.com/otaxhu/vidf"}"

      local version_tag
      version_tag="${1:-}"
      if [ -z "$version_tag" ]
      then
        _vidf_info "Checking for the latest remote version..."
        version_tag="$(
          git ls-remote --tags --refs "$repo_url" | \
          awk -F/ '{print $3}' | \
          grep -Ex 'v[0-9]+\.[0-9]+\.[0-9]+' | \
          sort -t . -k 1,1 -k 2,2 -k 3,3 -r | head -n1
        )"
        if [ -z "$version_tag" ]
        then
          _vidf_error "Couldn't determine the latest remote version. Try again."
          return 1
        fi
        _vidf_info "Found latest version" \
          "$(_vidf_style_bold)$version_tag$(_vidf_style_unbold)"
      else
        if ! _vidf_git_remote_tag_exists "$repo_url" "$version_tag"
        then
          _vidf_error "Version $(_vidf_style_bold)$version_tag$(_vidf_style_unbold) not found on remote"
          return 1
        fi
      fi

      local is_installing

      if ! [ -d "$install_dir/.git" ]
      then
        is_installing=1

        # Offer vidf installation to the user.

        # Print short GPL notice
        _vidf_err "Welcome to vidf (Version Manager for ESP-IDF)"
        _vidf_err "Copyright (C) 2026 Oscar Pernia"
        _vidf_err "This program comes with ABSOLUTELY NO WARRANTY."
        _vidf_err "This is free software, and you are welcome to redistribute it"
        _vidf_err "under certain conditions."
        _vidf_err ""

        if [ "$yes_flag" != 1 ]
        then
          _vidf_info "$(_vidf_style_bold)vidf ($version_tag)$(_vidf_style_unbold) is going to be installed on" \
            "$(_vidf_style_bold)$root_dir$(_vidf_style_unbold)"
          _vidf_info "If you wish to choose another directory for the installation, please cancel, set" \
            "$(_vidf_style_underline)VIDF_DIR$(_vidf_style_ununderline)" \
            "variable and try again."
          _vidf_user_confirms || return 1
        fi

        _vidf_info "Installing $(_vidf_style_bold)vidf ($version_tag)$(_vidf_style_unbold)" \
          "on $(_vidf_style_bold)$root_dir$(_vidf_style_unbold)..."
      else
        is_installing=0

        local cur_version
        # Don't use `vidf --version`, since the format for git tags is different.z
        if cur_version="$(_vidf_git_describe_dirty "$install_dir")"
        then
          if [ "$cur_version" != "${cur_version%"-dirty"}" ]
          then
            _vidf_warn "Detected modifications to vidf installation! If you continue you will lose those changes."
          elif [ "$cur_version" = "$version_tag" ]
          then
            _vidf_success "$(_vidf_style_bold)vidf$(_vidf_style_unbold) is already updated to version" \
              "$(_vidf_style_bold)$version_tag$(_vidf_style_unbold). Nothing to do!"
            return 0
          fi
        else
          cur_version="unknown"
          _vidf_warn "Couldn't determine the current vidf version using git. Attempting to update anyways"
        fi

        if [ "$yes_flag" != 1 ]
        then
          _vidf_info "$(_vidf_style_bold)vidf$(_vidf_style_unbold) is going to be updated to the following version:"
          _vidf_info "$(_vidf_style_bold)$cur_version$(_vidf_style_unbold) (currently installed) ->" \
            "$(_vidf_style_bold)$version_tag$(_vidf_style_unbold) (new)"

          _vidf_user_confirms || return 1
        fi

        _vidf_info "Updating $(_vidf_style_bold)vidf$(_vidf_style_unbold) to version" \
          "$(_vidf_style_bold)$version_tag$(_vidf_style_unbold)..."
      fi

      _vidf_git_ensure_switch "$install_dir" "$repo_url" "$version_tag" || return

      if [ "$is_installing" = 1 ]
      then
        _vidf_success "$(_vidf_style_bold)vidf$(_vidf_style_unbold) version" \
          "$(_vidf_style_bold)$version_tag$(_vidf_style_unbold) installed successfully"

        _vidf_err ""
        _vidf_err "$(_vidf_style_bold)Next steps to complete the installation:$(_vidf_style_unbold)"
        _vidf_err "Add the $(_vidf_style_underline)VIDF_DIR$(_vidf_style_ununderline)" \
          "directory and source the script by appending the following lines"
        _vidf_err "to your shell profile script (e.g., ~/.bashrc, ~/.zshrc, or ~/.profile):"
        _vidf_err "$(_vidf_style_bold)" # Command block start
        if [ "$root_dir" = "$HOME/.vidf" ]
        then
          _vidf_err "  export VIDF_DIR=\"\$HOME/.vidf\""
        else
          _vidf_err "  export VIDF_DIR=$(_vidf_sanitize_arg "$root_dir")"
        fi
        _vidf_err "  . \"\$VIDF_DIR/vidf/vidf\""
        _vidf_err "$(_vidf_style_unbold)" # Command block end
        _vidf_err "After adding it, restart your terminal or run source command"
      else
        _vidf_success "$(_vidf_style_bold)vidf$(_vidf_style_unbold) updated to version" \
          "$(_vidf_style_bold)$version_tag$(_vidf_style_unbold) succesfully"
      fi
      ;;
    install)
      local missing_dep
      missing_dep=0
      if ! _vidf_has git
      then
        missing_dep=1
        _vidf_error "$(_vidf_style_bold)git$(_vidf_style_unbold) not found on" \
          "$(_vidf_style_underline)PATH$(_vidf_style_ununderline)," \
          "this is a required dependency for the" \
          "$(_vidf_style_bold)install$(_vidf_style_unbold) subcommand."
      fi
      if ! _vidf_has python \
        && ! _vidf_has python3
      then
        missing_dep=1
        _vidf_error "$(_vidf_style_bold)python$(_vidf_style_unbold) not found on" \
          "$(_vidf_style_underline)PATH$(_vidf_style_ununderline)," \
          "this is a required dependency for the" \
          "$(_vidf_style_bold)install$(_vidf_style_unbold) subcommand."
      fi
      if ! _vidf_has curl
      then
        missing_dep=1
        _vidf_error "$(_vidf_style_bold)curl$(_vidf_style_unbold) not found on" \
          "$(_vidf_style_underline)PATH$(_vidf_style_ununderline)," \
          "this is a required dependency for the" \
          "$(_vidf_style_bold)install$(_vidf_style_unbold) subcommand."
      fi
      if ! _vidf_has jq
      then
        missing_dep=1
        _vidf_error "$(_vidf_style_bold)jq$(_vidf_style_unbold) not found on" \
          "$(_vidf_style_underline)PATH$(_vidf_style_ununderline)," \
          "this is a required dependency for the" \
          "$(_vidf_style_bold)install$(_vidf_style_unbold) subcommand."
      fi
      [ "$missing_dep" = 1 ] && return 1

      local yes_flag
      local repair_flag
      local targets_flag
      if ! eval "$(_vidf_parse_args_eval 0-1,-y,--repair,-t/--targets: yes_flag,repair_flag,targets_flag "$@")"
      then
        return 1
      fi

      local root_dir
      if ! root_dir="$(_vidf_app_dir)"
      then
        return 1
      fi

      local vidf_install_dir
      vidf_install_dir="$root_dir/vidf"

      local idf_versions_dir
      idf_versions_dir="$root_dir/idf-versions"

      local repo_url
      repo_url="${VIDF_INSTALL_IDF_GIT_URL:-"https://github.com/espressif/esp-idf"}"

      local idf_version_tag
      idf_version_tag="$1"
      if [ -z "$idf_version_tag" ]
      then
        _vidf_info "Checking for the latest" \
          "$(_vidf_style_bold)ESP-IDF$(_vidf_style_unbold)" \
          "remote version..."
        idf_version_tag="$(
          git ls-remote --tags --refs "$repo_url" |
          awk -F/ '{print $3}' |
          # Weird version naming convention from ESP-IDF, they aren't following semver
          grep -Ex 'v[0-9]+\.[0-9]+(\.[0-9]+)?' |
          sort -t . -k 1,1 -k 2,2 -k 3,3 -r | head -n1
        )"
        if [ -z "$idf_version_tag" ]
        then
          _vidf_error "Couldn't determine the latest" \
            "$(_vidf_style_bold)ESP-IDF$(_vidf_style_unbold)" \
            "remote version. Try again."
          return 1
        fi
        _vidf_info "Found latest remote version" \
          "$(_vidf_style_bold)$idf_version_tag$(_vidf_style_unbold)"
      else
        if ! _vidf_git_remote_tag_exists "$repo_url" "$idf_version_tag"
        then
          _vidf_error "Version $(_vidf_style_bold)$idf_version_tag$(_vidf_style_unbold) not found on remote"
          return 1
        fi
      fi

      _vidf_info "Checking target board compatibility for" \
        "$(_vidf_style_bold)ESP-IDF ($idf_version_tag)$(_vidf_style_unbold)..."

      local idf_versions_json
      if ! idf_versions_json="$(_vidf_download_file "https://dl.espressif.com/dl/esp-idf/idf_versions.json")"
      then
        _vidf_error "Couldn't determine available target boards"
        return 2
      fi

      local is_original_json
      ! jq -e 'type == "object"' "$idf_versions_json" >/dev/null
      is_original_json="$?"

      # Compact JSON and move results to cache dir, only if it's original JSON
      #
      # Findings:
      #
      # There is an issue with the original JSON file, there is duplicated "name"
      # keys in "VERSIONS" array, as well as duplicated values in
      # "supported_targets" array, we de-duplicate them.
      #
      # We don't support "pre_release"s and "latest" versions, since those doesn't
      # exists as git tags in the git repository, filter them out as well.
      if [ "$is_original_json" = 1 ]
      then
        local temp_json
        temp_json="$(mktemp)"

        local jq_exit_code
        jq_exit_code=0

        if ! jq -c '
          .VERSIONS | unique_by(.name) |
          map(
            # Discards pre_releases, latest versions and objects with empty supported_targets
            select(.pre_release or .name == "latest" or (.supported_targets // [] | length == 0) | not) |
            {
              name: .name,
              supported_targets: .supported_targets | unique
            }
          )
        ' "$idf_versions_json" > "$temp_json"
        then
          jq_exit_code=1
          _vidf_error "Couldn't compact $(_vidf_style_bold)idf_versions.json$(_vidf_style_unbold)." \
            "Please file an issue!"
        elif ! mv -f "$temp_json" "$idf_versions_json"
        then
          jq_exit_code=1
          _vidf_error "Couldn't move compacted $(_vidf_style_bold)idf_versions.json$(_vidf_style_unbold)" \
            "into cache directory"
        fi

        if [ "$jq_exit_code" != 0 ]
        then
          rm -f "$temp_json"
          return 2
        fi
      fi

      # JSON array of strings
      local supported_targets
      if ! supported_targets="$(
        jq -c --arg tag "$idf_version_tag" '
          .[] | select(.name == $tag) | .supported_targets
        ' "$idf_versions_json"
      )"
      then
        _vidf_error "Couldn't parse $(_vidf_style_bold)idf_versions.json$(_vidf_style_unbold)." \
          "Please file an issue!"
        return 2
      fi

      if [ -n "$targets_flag" ]
      then
        targets_flag="$(
          _vidf_echo "$targets_flag" |
          tr ',' '\n' |
          while IFS="" read -r line
          do
            printf " %s" "$(_vidf_sanitize_arg "$line")"
          done
        )"

        # Check that targets work on selected version tag
        local unsupported_targets
        if ! unsupported_targets="$(
          _vidf_echo "$targets_flag" | xargs \
            jq -rn --arg-json supported "$supported_targets" '
              $ARGS.positional[] | select(. as $input | $supported | index($input) | not)
            ' --args --
        )"
        then
          _vidf_error "Couldn't determine incompatible target boards. Please file an issue!"
          return 2
        fi

        if [ -n "$unsupported_targets" ]
        then
          _vidf_error "The following board targets specified in" \
            "$(_vidf_style_bold)--targets$(_vidf_style_unbold) flag are unsupported for" \
            "$(_vidf_style_bold)ESP-IDF ($idf_version_tag)$(_vidf_style_unbold):" \
            "$(_vidf_style_bold)$(_vidf_echo "$unsupported_targets" | tr "\n" " ")$(_vidf_style_unbold)"
          return 1
        fi
      else
        local supported_targets_sh
        supported_targets_sh="$(
          jq -rn --argjson supported "$supported_targets" '
            $supported[]
          ' |
          while read -r line
          do
            printf " %s" "$(_vidf_sanitize_arg "$line")"
          done
        )"

        # Ask user for which ESP boards he is targetting
        if ! targets_flag="$(
          eval "_vidf_user_multi_select \"Select ESP-IDF target boards to install\" $supported_targets_sh"
        )"
        then
          return 1
        fi
        if [ -z "$targets_flag" ]
        then
          _vidf_error "You must select at least 1 target board"
          return 1
        fi
      fi

      # Directory where ESP-IDF is going to be cloned into.
      local install_dir
      install_dir="$idf_versions_dir/$idf_version_tag"

      if ! [ -d "$install_dir/.git" ]
      then
        # Disable repair_flag in order to show proper success message below.
        repair_flag=0
        if [ "$yes_flag" != 1 ]
        then
          _vidf_info "$(_vidf_style_bold)ESP-IDF ($idf_version_tag)$(_vidf_style_unbold)" \
            "is going to be installed."
          _vidf_info "With the following target boards:" \
            "$(_vidf_style_bold)$(_vidf_echo "$targets_flag" | xargs)$(_vidf_style_bold)"
          _vidf_user_confirms || return
        fi

        _vidf_info "Installing $(_vidf_style_bold)ESP-IDF ($idf_version_tag)$(_vidf_style_unbold)..."
      else
        local cur_version
        if cur_version="$(_vidf_git_describe_dirty "$install_dir")"
        then
          if [ "$cur_version" != "${cur_version%"-dirty"}" ]
          then
            _vidf_warn "Detected modifications to" \
              "$(_vidf_style_bold)ESP-IDF ($idf_version_tag)$(_vidf_style_unbold)" \
              "installation!"
          elif [ "$cur_version" = "$idf_version_tag" ] && [ "$repair_flag" != 1 ]
          then
            _vidf_success "$(_vidf_style_bold)ESP-IDF ($idf_version_tag)$(_vidf_style_unbold)" \
              "already installed. Nothing to do!"
            return 0
          fi
        else
          _vidf_warn "$(_vidf_style_bold)ESP-IDF ($idf_version_tag)$(_vidf_style_unbold)" \
            "installation corrupted."
        fi
        if [ "$repair_flag" != 1 ]
        then
          _vidf_info "Use $(_vidf_style_bold)--repair$(_vidf_style_unbold)" \
            "in order to repair this version."
          return 0
        fi

        _vidf_info "Repairing" \
          "$(_vidf_style_bold)ESP-IDF ($idf_version_tag)$(_vidf_style_unbold)..."
      fi

      _vidf_git_ensure_switch "$install_dir" "$repo_url" "$idf_version_tag" || return

      _vidf_info "Applying patches to ESP-IDF..."
      if ! git apply --no-index --directory="$install_dir" --quiet -R --check "$vidf_install_dir"/patches/esp-idf/*.patch
      then
        if ! git apply --no-index --directory="$install_dir" "$vidf_install_dir"/patches/esp-idf/*.patch
        then
          _vidf_error "Couldn't apply patches to ESP-IDF installation. Please file an issue!"
          return 2
        fi
      fi

      _vidf_info "Running $(_vidf_style_bold)install.sh$(_vidf_style_unbold)..."
      if ! _vidf_echo "$targets_flag" | xargs sh -- "$install_dir/install.sh"
      then
        _vidf_error "$(_vidf_style_bold)install.sh$(_vidf_style_unbold) failed to run"
        return 2
      fi

      if [ "$repair_flag" = 1 ]
      then
        _vidf_success "$(_vidf_style_bold)ESP-IDF ($idf_version_tag)$(_vidf_style_unbold)" \
          "was succesfully repaired."
      else
        _vidf_success "$(_vidf_style_bold)ESP-IDF ($idf_version_tag)$(_vidf_style_unbold)" \
          "was succesfully installed."
      fi

      _vidf_err ""
      _vidf_err "In order to activate your ESP-IDF environment, run:"
      _vidf_err "$(_vidf_style_bold)" # Command start block
      _vidf_err "  vidf use $(_vidf_sanitize_arg "$idf_version_tag")"
      _vidf_err "$(_vidf_style_unbold)" # Command end block
      ;;
    *)
      _vidf_error "Unknown subcommand: $subcommand"
      _vidf_help_render >&2
      return 1
      ;;
  esac
}

if ! _vidf_is_sourced && [ "$_VIDF_TEST" != 1 ]
then
  # Initial setup for colors
  _VIDF_STYLE_SETUP=1 vidf "$@" || exit "$?"

  if ! [ -e "$(_vidf_app_dir)" ]
  then
    # Assume the user is running the script for the first time and is
    # piping it, most likely from curl.

    # Trigger auto-installation. Bypass flags that may be included such as -y
    _vidf_info "No installation found. Running: $(_vidf_style_bold)vidf self-update $*"

    vidf self-update "$@"
    _EXIT_CODE="$?"
    if [ "$_EXIT_CODE" != 0 ]
    then
      _vidf_error "Cleaning up failed installation..."
      rm -rf "$(_vidf_app_dir)"
    fi

    exit "$_EXIT_CODE"
  fi

  _vidf_error "You must source this script in order to use it."
  exit 1
fi

# @formatter:off
} # Ensures the entire script is downloaded
# @formatter:on
