#!/bin/sh
# shellcheck disable=SC3043

# vidf - Version Manager for ESP-IDF.
#
# Copyright (C) 2026 Oscar Pernia
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Implemented as a POSIX-compliant shell function. To initialize the tool,
# this script must be executed directly at least once to trigger the installation.
# Subsequent executions and daily usage require sourcing the script to manage
# ESP-IDF environments correctly.
#
# This tool is inspired by NVM (Node Version Manager) project,
# but for managing ESP-IDF (Espressif IoT Development Framework) installations
# and environments.

# @formatter:off
{ # Ensures the entire script is downloaded
# @formatter:on

_VIDF_VERSION="0.1.0-devel"

_vidf_is_sourced ()
{
  if [ -n "$ZSH_VERSION" ]
  then
    case "$ZSH_EVAL_CONTEXT" in
      *:file:*|*:file|file:*|file)
        return 0
        ;;
    esac
  else  # Add additional POSIX-compatible shell names here, if needed.
    case "${0##*/}" in
      dash|-dash|bash|-bash|ksh|-ksh|sh|-sh)
        return 0
        ;;
    esac
  fi
  return 1
}

_vidf_echo()
{
  while [ "$#" -gt 1 ]
  do
    printf "%s " "$1"
    shift
  done
  printf "%s\n" "${1:-}"
}

_vidf_err()
{
  _vidf_echo "$@" >&2
}

_vidf_error()
{
  _vidf_err "$(_vidf_style_red)$*$(_vidf_style_reset)"
}

_vidf_warn()
{
  _vidf_err "$(_vidf_style_yellow)$*$(_vidf_style_reset)"
}

_vidf_info()
{
  _vidf_err "$(_vidf_style_cyan)$*$(_vidf_style_reset)"
}

_vidf_success()
{
  _vidf_err "$(_vidf_style_green)$*$(_vidf_style_reset)"
}

_vidf_has()
{
  type "${1-}" >/dev/null 2>&1
  return "$?"
}

# You must pass to it at least 2 arguments, the predicate and the cancelled message.
# A default value is provided for this two, so you can pass empty strings.
_vidf_user_confirms()
{
  local predicate
  predicate="${1:-"Is this ok?"} [y/N]: "

  local cancelled
  cancelled="${2:-"Operation cancelled."}"

  printf "%s" "$predicate" >&2

  local opt
  local read_exit_code
  while true
  do
    read -r opt
    read_exit_code="$?"
    # Fixes visual bug where if you pipe `yes | vidf ...` you are going to
    # have the lines squished up on the same line.
    if ! [ -t 0 ] || [ "$read_exit_code" -ne 0 ]
    then
      _vidf_err ""
      [ "$read_exit_code" -ne 0 ] && break
    fi
    case "$opt" in
      [yY][eE][sS]|[yY])
        return 0
        ;;
      [nN][oO]|[nN]|"")
        break
        ;;
      *)
        printf "Please enter (y)es or (n)o: " >&2
        ;;
    esac
  done

  _vidf_error "$cancelled"
  return 1
}

_vidf_app_dir()
{
  local app_dir
  app_dir="${VIDF_DIR:-"$HOME/.vidf"}"

  if [ "$app_dir" = "${app_dir#/}" ]
  then
    if [ -n "${VIDF_DIR:-}" ]
    then
      _vidf_error "$(_vidf_style_underline)VIDF_DIR$(_vidf_style_ununderline)" \
        "variable must be an absolute path."
    else
      _vidf_error "$(_vidf_style_underline)HOME$(_vidf_style_ununderline)" \
        "variable must be an absolute path."
    fi
    return 1
  fi

  _vidf_echo "$app_dir"
  return 0
}

# Output is already quoted.
_vidf_sanitize_arg()
{
  local sanitized

  sanitized="$(printf "%s" "$1" | sed "s/'/'\\\\''/")"

  printf "'%s'" "$sanitized"
}

# Canonizes flags, converts them from the form:
#
#   --foo=bar -abc
#
# To:
#
#   --foo 'bar' -a -b -c
#
# The $1 format is similar to the one on _vidf_check_args, except that you must
# trim the arguments range from the beginning, e.g:
#
# "-y,--prefix:,-h,--help"
_vidf_canonize_args()
{
  local flags
  # Normalize flags, separate in newlines, apply colons to all aliases that
  # end on colon (:), and finally one last separation with newlines of aliases.
  # We don't use the slashes because this command is indifferent regarding aliases,
  # aliases overwrite other aliases.
  flags="$(_vidf_echo "$1" | awk '
    BEGIN {
      FS = ","

      short_opts = ""
      long_opts = ""
    }
    {
      for (i = 1; i <= NF; i++)
        {
          alias_group = $i
          has_colon = sub(/:$/, "", alias_group) > 0
          n_aliases = split(alias_group, aliases, "/")
          for (j = 1; j <= n_aliases; j++)
            {
              alias = aliases[j] (has_colon ? ":" : "")

              if (sub(/^--/, "", alias))
                {
                  long_opts = (long_opts == "") ? alias : long_opts "," alias
                }
              else
                {
                  sub(/^-/, "", alias)
                  short_opts = short_opts alias
                }
            }
        }
    }
    END {
      print short_opts, long_opts
    }
  ')"
  shift

  local short_opts
  short_opts="${flags%" "*}"
  local long_opts
  long_opts="${flags#*" "}"

  local temp_err
  temp_err="$(mktemp)"

  local getopt_exit_code
  getopt_exit_code=0
  if ! LANGUAGE=C getopt -o "$short_opts" -l "$long_opts" -- "$@" 2>"$temp_err"
  then
    getopt_exit_code=1
    _vidf_error "$(sed -E 's/^getopt:\s*(.)/\u\1/' "$temp_err")"
  fi

  rm -rf "$temp_err"
  return "$getopt_exit_code"
}

# Same as _vidf_canonize_args, but the output of this function is safe to be
# passed to `eval` command in order to set the canonized arguments.
_vidf_canonize_args_eval()
{
  local flags
  flags="$1"
  shift

  local parsed_args

  if ! parsed_args="$(_vidf_canonize_args "$flags" "$@")"
  then
    _vidf_echo "false"
    return 0
  fi

  printf "set -- %s\n" "$parsed_args"

  return 0
}

# NOTE: We don't use getopts because it doesn't accept long options
#
# The $1 format parameter is similar to getopts format, except that
# it starts with the minimum and maximum number of required positional
# arguments, followed by a comma-separated list of valid short and long
# options. You can also pass a plus sign (+) after the minimum required
# positional arguments to indicate the user can pass infinite arguments.
# You can also pass aliased flags, you can have multiple aliased flags.
#
# User arguments must be canonized with _vidf_canonize_args_eval function.
#
# Basic format:
# "2,-y,--prefix:,--version"
#
# Format for variadic arguments, minimum 0 args and maximum 2 args:
# "0-2,-y,--prefix:,--version"
#
# Infinite arguments, minimum 1:
# "1+,-y,--prefix:,--version"
#
# Aliased flags:
# "2,-y/--yes,-p/--prefix:"
_vidf_check_args()
{
  local format
  format="$1"
  shift

  local expected_arg_range
  expected_arg_range="${format%%,*}"

  local flags
  flags="${format#*,}"

  # Separate in newlines for better handling.
  flags="$(_vidf_echo "$flags" | sed 's/,/\n/g')"

  local expected_min_args
  local expected_max_args
  case "$expected_arg_range" in
    *+)
      expected_min_args="${expected_arg_range%+}"
      expected_max_args=-1
      ;;
    *-*)
      expected_min_args="${expected_arg_range%%-*}"
      expected_max_args="${expected_arg_range#*-}"
      ;;
    *)
      expected_min_args="$expected_arg_range"
      expected_max_args="$expected_arg_range"
      ;;
  esac

  local arg_count
  arg_count=0

  local matched_flag

  while [ "$#" -gt 0 ]
  do
    case "$1" in
      --)
        shift
        arg_count="$((arg_count + $#))"
        break
        ;;
      -*[!-a-zA-Z0-9]*)
        # Contains invalid characters.
        _vidf_error "Unrecognized option '$1'"
        return 1
        ;;
      -*)
        if ! matched_flag="$(_vidf_echo "$flags" | grep -E "(^|/)$1(:|\$|/)")"
        then
          _vidf_error "Unrecognized option '$1'"
          return 1
        fi

        if [ "$matched_flag" != "${matched_flag%:}" ]
        then
          if [ "$#" -lt 2 ]
          then
            _vidf_error "Option '$1' requires an argument"
            return 1
          fi

          shift 2
          continue
        fi

        shift
        continue
        ;;
      *)
        arg_count=$((arg_count + 1))
        shift
        ;;
    esac
  done

  if [ "$arg_count" -lt "$expected_min_args" ]
  then
    _vidf_error "Too few arguments. Expected at least $expected_min_args, got $arg_count."
    return 1
  fi

  if [ "$expected_max_args" -ne -1 ] && [ "$arg_count" -gt "$expected_max_args" ]
  then
    _vidf_error "Too many arguments. Expected at most $expected_max_args, got $arg_count."
    return 1
  fi
}

# This function outputs to stdout a shell program to be eval'd by the caller,
# which is going to parse the arguments/flags of the user, and save it to
# flag variables specified on $2, and the parsed positional arguments are going
# to be saved on the caller's argument list, e.g. $1, $2, $3, ..., $N, etc.
#
# Function's parameters:
#
# - $1: Format specifier, see _vidf_check_args.
#
# - $2: Comma-separated flag shell variables list, their positions must correspond to
# the positions on the format specifier, if the format specifier doesn't list
# any flags, then you MUST NOT pass this argument, not even an empty string,
# you must directly pass the user's $@ list after $1.
#
# - $@: User's arguments, must be canonized.
_vidf_parse_args_eval()
{
  local format
  format="$1"
  shift

  local flag_vars
  [ -n "${format#*,}" ] && flag_vars="$1" && shift

  if ! _vidf_check_args "$format" "$@"
  then
    _vidf_echo "false"
    return 0
  fi

  local expected_flags
  expected_flags="${format#*,}"

  # Separate in newlines for better handling
  expected_flags="$(printf "%s" "$expected_flags" | sed 's/,/\n/g')"
  flag_vars="$(printf "%s" "$flag_vars" | sed 's/,/\n/g')"

  local matched_flag
  local target_var
  local flag_line_num

  local set_args_eval
  while [ "$#" -gt 0 ]
  do
    case "$1" in
      --)
        shift
        while [ "$#" -gt 0 ]
        do
          set_args_eval="$set_args_eval $(_vidf_sanitize_arg "$1")"
          shift
        done
        break
        ;;
      -*)
        matched_flag="$(_vidf_echo "$expected_flags" | awk '
          /(^|\/)'"$1"'(:|$|\/)/ {
            print NR, $0
            exit
          }
        ')"

        flag_line_num="${matched_flag%%" "*}"
        matched_flag="${matched_flag#*" "}"

        target_var="$(_vidf_echo "$flag_vars" | sed -n "${flag_line_num}p")"

        if [ "$matched_flag" != "${matched_flag#*:}" ]
        then
          shift
          _vidf_echo "$target_var=$(_vidf_sanitize_arg "$1")"
        else
          _vidf_echo "$target_var=1"
        fi
        ;;
      *)
        set_args_eval="$set_args_eval $(_vidf_sanitize_arg "$1")"
        ;;
    esac
    shift
  done

  printf "set --%s\n" " $set_args_eval"
}

# Returns the first argument that is not an option nor its value.
#
# $@ - User's arguments, this are required to be non-canonized due to the fact
#      that the subcommand is treated as a regular positional argument.
_vidf_find_subcommand()
{
  local skip_arg
  skip_arg=0
  local i

  for i in "$@"
  do
    if [ "$skip_arg" = 1 ]
    then
      skip_arg=0
      continue
    fi

    case "$i" in
      --color)
        # Add to pattern above known global options on canonical form that
        # contains a value.
        skip_arg=1
        ;;
      -*)
        ;;
      *)
        local subcommand
        subcommand="$i"
        [ -z "$subcommand" ] && return 1
        _vidf_echo "$subcommand"
        return 0
        ;;
    esac
  done

  return 1
}

# Removes the subcommand and return everything else as an space separated list.
#
# $@ - User's arguments, this are required to be non-canonized due to the fact
#      that the subcommand is treated as a regular positional argument.
_vidf_filter_subcommand()
{
  if [ "$#" -lt 1 ]
  then
    return 0
  fi

  local subcommand_found
  subcommand_found=0
  local skip_arg
  skip_arg=0
  local i
  for i in "$@"
  do
    if [ "$skip_arg" = 1 ] || [ "$subcommand_found" = 1 ]
    then
      skip_arg=0
      printf " %s" "$(_vidf_sanitize_arg "$i")"
      continue
    fi

    case "$i" in
      --color)
        skip_arg=1
        printf " %s" "$(_vidf_sanitize_arg "$i")"
        ;;
      -*)
        printf " %s" "$(_vidf_sanitize_arg "$i")"
        ;;
      *)
        subcommand_found=1
        ;;
    esac
  done

  _vidf_echo ""
}

# See _vidf_filter_subcommand, outputs a program to be eval'd by the caller,
# which is going to filter out the subcommand from user's arguments.
# You must have already called _vidf_find_subcommand in order to get the subcommand
# before eval'ing this function's output, and pass that as the first argument.
_vidf_filter_subcommand_eval()
{
  local subcommand
  subcommand="$1"
  shift

  local filtered
  if ! filtered="$(_vidf_filter_subcommand "$subcommand" "$@")"
  then
    _vidf_echo "false"
    return 1
  fi

  printf "set -- %s" "$filtered"
}

# ANSI color styles logic. {{{

_VIDF_COLOR=1

_vidf_style_setup()
{
  if [ "$#" -gt 0 ]
  then
    if [ "$1" = 1 ]
    then
      _VIDF_COLOR=1
    else
      _VIDF_COLOR=0
    fi
  elif [ -t 1 ]
  then
    _VIDF_COLOR=1
  else
    _VIDF_COLOR=0
  fi
}

_vidf_style_reset()
{
  [ "$_VIDF_COLOR" = "1" ] && printf "\033[0m"
}

_vidf_style_bold()
{
  [ "$_VIDF_COLOR" = "1" ] && printf "\033[1m"
}

_vidf_style_underline()
{
  [ "$_VIDF_COLOR" = "1" ] && printf "\033[4m"
}

_vidf_style_red()
{
  [ "$_VIDF_COLOR" = "1" ] && printf "\033[31m"
}

_vidf_style_green()
{
  [ "$_VIDF_COLOR" = "1" ] && printf "\033[32m"
}

_vidf_style_yellow()
{
  [ "$_VIDF_COLOR" = "1" ] && printf "\033[33m"
}

_vidf_style_cyan()
{
  [ "$_VIDF_COLOR" = "1" ] && printf "\033[36m"
}

_vidf_style_unbold()
{
  [ "$_VIDF_COLOR" = "1" ] && printf "\033[22m"
}

_vidf_style_ununderline()
{
  [ "$_VIDF_COLOR" = "1" ] && printf "\033[24m"
}

_vidf_style_uncolor()
{
  [ "$_VIDF_COLOR" = "1" ] && printf "\033[39m"
}

# }}}

# Rendering help message logic. {{{
# Simple manpage-like help message.

_vidf_help_render()
{
  local line
  while IFS="" read -r line
  do
    case "$line" in
      USAGE|COMMANDS|OPTIONS)
        # Title sections styles
        printf "%s%s" "$(_vidf_style_bold)" "$line"
        ;;
      "$(printf "%*s" 4 "")"[a-zA-Z0-9]*)
        # Commands styles
        printf "%s%s" "$(_vidf_style_bold)" "$line"
        ;;
      "$(printf "%*s" 12 "")"-*)
        # Command option styles
        printf "%s%s" "$(_vidf_style_bold)" "$line"
        ;;
      *)
        # Bypass styles
        printf "%s" "$line"
        ;;
    esac
    printf "%s\n" "$(_vidf_style_reset)"

  done << EOF # You can add more styles to the here-doc below if the above ones doesn't fully style it.

vidf - Version Manager for ESP-IDF ($(vidf --version))

USAGE
    vidf <command> [options ...] [--] [arguments ...]

COMMANDS
    self-update [$(_vidf_style_underline)version$(_vidf_style_ununderline)]
        Updates vidf to the latest release. If a specific $(_vidf_style_underline)version$(_vidf_style_ununderline)
        is provided, that version will be installed instead.

        Options:
            -y
                Automatic yes to all prompts.

OPTIONS
    -h, --help
        Shows this message.

    --color <$(_vidf_style_underline)WHEN$(_vidf_style_ununderline)>
        Controls color output. Can be 'always', 'never', or 'auto' (default).

    -v, --version
        Prints currently installed vidf version and exits.

    --
        Delimits end of option processing. Any subsequent arguments
        are treated strictly as positional arguments.
EOF
}

# }}}

vidf()
{
  # Handle shell flags first, this is in order to avoid any unexpected
  # behaviours before executing any important commands that modifies the system.

  local default_ifs
  default_ifs=" $(_vidf_echo t | command tr t \\t)
"
  case "$-" in
    *e*)
      set +e
      local exit_code
      IFS="$default_ifs" vidf "$@"
      exit_code="$?"
      set -e
      return "$exit_code"
      ;;
    *a*)
      set +a
      local exit_code
      IFS="$default_ifs" vidf "$@"
      exit_code="$?"
      set -a
      return "$exit_code"
      ;;
    *E*)
      # Only if running on Bash
      if [ -n "${BASH-}" ]
      then
        # shellcheck disable=SC3041
        set +E
        local exit_code
        IFS="$default_ifs" vidf "$@"
        exit_code="$?"
        # shellcheck disable=SC3041
        set -E
        return "$exit_code"
      fi
      ;;
    *)
      if [ "$IFS" != "$default_ifs" ]
      then
        IFS="$default_ifs" vidf "$@"
        return "$?"
      fi
      ;;
  esac

  # First setup based on tty detection.
  _vidf_style_setup

  # {{{
  # Extract and filter out subcommand, canonize user's arguments, filter and
  # handle all global options from the canonized arguments.

  # Find subcommand
  local subcommand
  subcommand="$(_vidf_find_subcommand "$@")"

  # Filter out subcommand
  eval "$(_vidf_filter_subcommand_eval "$@")"

  local global_format
  global_format="--help,-h,--version,-v,--color:"

  # Add here additional options for each subcommand, they must not conflict
  # with the global options names.
  case "$subcommand" in
    self-update)
      global_format="$global_format,-y"
      ;;
  esac

  # Canonize the arguments.
  if ! eval "$(_vidf_canonize_args_eval "$global_format" "$@")"
  then
    return 1
  fi

  local i
  local eoo # End Of Options, is -- present?
  eoo=0
  local flag_action

  local invalid_value
  invalid_value=0

  local skip_arg
  skip_arg=0

  local err_msg

  # Handle global options
  for i in "$@"
  do
    # Circular shift filter, in order to remove global options.
    shift

    if [ "$skip_arg" = 1 ]
    then
      skip_arg=0
      continue
    fi

    if [ "$eoo" = 1 ]
    then
      set -- "$@" "$i"
      continue
    fi

    case "$i" in
      --)
        eoo=1
        set -- "$@" "$i"
        ;;
      -h|--help)
        flag_action=help
        ;;
      --color)
        case "$1" in
          always)
            _vidf_style_setup 1
            ;;
          never)
            _vidf_style_setup 0
            ;;
          auto)
            _vidf_style_setup
            ;;
          *)
            err_msg="$(printf "%s${err_msg:+"\n"}Invalid value for --color: '%s'" "$err_msg" "$1")"
            invalid_value=1
            ;;
        esac

        skip_arg=1
        ;;
      -v|--version)
        # Add here the flag actions that may have higher priority
        case "$flag_action" in
          help)
            :
            ;;
          *)
            flag_action=version
            ;;
        esac
        ;;
      *)
        set -- "$@" "$i"
        ;;
    esac
  done

  # }}}
  # End of canonization, at this point the we've handled global options.

  if [ "$invalid_value" = 1 ]
  then
    _vidf_error "$err_msg"
    _vidf_help_render >&2
    return 1
  fi

  case "$flag_action" in
    help)
      _vidf_help_render
      return 0
      ;;
    version)
      _vidf_echo "$_VIDF_VERSION"
      return 0
      ;;
  esac

  if [ -z "$subcommand" ]
  then
    _vidf_error "You must specify a subcommand."
    _vidf_help_render >&2
    return 1
  fi

  case "$subcommand" in
    self-update)
      if ! _vidf_has git
      then
        _vidf_error "$(_vidf_style_underline)git$(_vidf_style_ununderline) not found on PATH," \
                    "this is a required dependency for the" \
                    "$(_vidf_style_bold)self-update$(_vidf_style_unbold) subcommand."
        return 1
      fi

      local yes_flag
      if ! eval "$(_vidf_parse_args_eval 0-1,-y yes_flag "$@")"
      then
        return 1
      fi
      if ! [ -e "$(_vidf_app_dir)/vidf" ]
      then
        # Offer vidf installation to the user.

        # Print short GPL notice
        _vidf_err "Welcome to vidf (Version Manager for ESP-IDF)"
        _vidf_err "Copyright (C) 2026 Oscar Pernia"
        _vidf_err "This program comes with ABSOLUTELY NO WARRANTY."
        _vidf_err "This is free software, and you are welcome to redistribute it"
        _vidf_err "under certain conditions."
        _vidf_err ""

        _vidf_info "$(_vidf_style_bold)vidf$(_vidf_style_unbold) is going to be installed on" \
                   "$(_vidf_style_bold)$(_vidf_app_dir)$(_vidf_style_unbold)"
        _vidf_info "If you wish to choose another directory for the installation, please cancel, set" \
                   "$(_vidf_style_underline)VIDF_DIR$(_vidf_style_ununderline)" \
                   "variable and try again."
        if ! _vidf_user_confirms
        then
          return 1
        fi
      fi

      # TODO: All of the vidf repository cloning logic
      if _vidf_has git
      then
        :
      elif _vidf_has curl
      then
        :
      elif _vidf_has wget
      then
        :
      else
        _vidf_error "Needs one of \`git\`, \`curl\` or \`wget\` in order to install vidf."
        return 1
      fi

      # TODO: The rest of the logic for `self-update`-ing
      ;;
    *)
      _vidf_error "Unknown subcommand: $subcommand"
      _vidf_help_render >&2
      return 1
      ;;
  esac
}

if ! _vidf_is_sourced && [ "$_VIDF_TEST" != 1 ]
then
  # Initial setup for colors
  vidf --help "$@" >/dev/null 2>&1

  if ! [ -e "$(_vidf_app_dir)" ]
  then
    # Assume the user is running the script for the first time and is
    # piping it, most likely from curl.

    # Trigger auto-installation. Bypass flags that may be included such as -y
    _vidf_info "No installation found. Running: $(_vidf_style_bold)vidf self-update $*"

    vidf self-update "$@"
    exit "$?"
  fi

  _vidf_error "You must source this script in order to use it."
  exit 1
fi

# @formatter:off
} # Ensures the entire script is downloaded
# @formatter:on
