name: CI

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install ShellCheck
        run: |
          echo "Downloading ShellCheck 0.11.0 release..."
          scversion="v0.11.0"
          wget -qO- "https://github.com/koalaman/shellcheck/releases/download/${scversion}/shellcheck-${scversion}.linux.x86_64.tar.xz" | tar -xJv

          sudo mv "shellcheck-${scversion}/shellcheck" /usr/local/bin/

          shellcheck --version

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Install Beautysh
        run: pip install beautysh

      - name: Run ShellCheck Static Analysis
        id: shellcheck_step
        continue-on-error: true
        run: |
          echo "Checking scripts with ShellCheck..."
          shellcheck -x vidf *.sh hooks/*

      - name: Verify Code Formatting (Beautysh)
        id: beautysh_step
        continue-on-error: true
        run: |
          echo "Verifying code style consistency..."
          beautysh --check -i 2 vidf *.sh hooks/*

      - name: Check Assertions Status
        run: |
          if [ "${{ steps.shellcheck_step.outcome }}" = "failure" ] ||
            [ "${{ steps.beautysh_step.outcome }}" = "failure" ]
          then
            echo "❌ Some QA assertions failed. Review the logs above for ShellCheck or Beautysh errors."
            exit 1
          fi
